name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SPEC_PATH: mocks/openapi-billing.yml
      API_URL: http://127.0.0.1:4010
      CONTRACT_OK: '12345'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Show spec
        run: |
          ls -la $(dirname "$SPEC_PATH") || true
          head -n 30 "$SPEC_PATH" || true

      - name: Start Prism
        run: |
          npx -y @stoplight/prism-cli@5 mock -h 0.0.0.0 -p 4010 "$SPEC_PATH" > prism.log 2>&1 &
          echo $! > prism.pid

      - name: Wait for Prism
        run: |
          for i in {1..60}; do
            if (echo > /dev/tcp/127.0.0.1/4010) >/dev/null 2>&1; then
              echo "Prism is up"; break; fi
            sleep 1
          done
          for i in {1..40}; do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Accept: application/json" \
              -H "Authorization: Bearer anything" \
              "$API_URL/$CONTRACT_OK/invoices")
            if [ "$CODE" != "000" ]; then
              echo "Prism answered with HTTP $CODE"; exit 0; fi
            sleep 2
          done
          echo "Prism did not respond"; tail -n 50 prism.log || true; exit 1

      - run: npm test

      - name: Prism logs on failure
        if: failure()
        run: tail -n 200 prism.log || true

      - name: Stop Prism
        if: always()
        run: kill $(cat prism.pid) || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            prism.log
            reports/**
          if-no-files-found: ignore
